version: "3.8"

services:
  consumer:
    image: consumer
    container_name: docker-consumer
    ports:
    - "9098:9098"
    networks:
      - producer-consumer
    depends_on:
      - producer
  producer:
      image: producer
      container_name: docker-producer
      ports:
      - "9090:9090"
      networks:
        - producer-consumer
      depends_on:
        - mysql
  mysql:
    image: mysql:8
    container_name: mysql-db
    ports:
    - 3306:3306
    networks:
      - producer-consumer
    environment:
      - MYSQL_ROOT_PASSWORD=14292
      - MYSQL_DATABASE=HR
      - MYSQL_USER=root

networks:
  producer-consumer:
